[[headers]]
  filter = "**/*.html"
  [headers."**/*.html"]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  filter = "**/*.{js,css}"
  [headers."**/*.{js,css}"]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  filter = "**/*.{jpg,jpeg,png,gif,svg}"  
  [headers."**/*.{jpg,jpeg,png,gif,svg}"]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  filter = "/_nuxt/**"
  [headers."/_nuxt/**"]
    Cache-Control = "no-cache, no-store, must-revalidate"

